### ISSUE TITLE
Producer UI Testing Plans

### ISSUE THREAD

**Issue by emccoy5** [cs210/ABC-Virtual-Anchor#12]
Create a producer testing plan to be able to effectively gather feedback from producers. Identify an essential question we want to answer from testing. (RITE testing method)

**Comment by ishakumar** [comment]
Testing guide can be found [here](https://docs.google.com/document/d/1FabgDONeVmlaSUAGu2qD7QCJjEn0jEBIXm322T0fur4/edit).
