### ISSUE TITLE
Fix Software Architecture Diagram

### ISSUE THREAD

**Issue by ishakumar** [cs210/ABC-Virtual-Anchor#17]
Update our architecture diagram to reflect removed A.I. components and added reintegration with Blender.

**Comment by SajanaW** [comment]
Here's a more detailed Software Architecture Diagram @ishakumar 
[CS210BackEnd_detail_sketch.pdf](https://github.com/cs210/ABC-Virtual-Anchor/files/4310175/CS210BackEnd_detail_sketch.pdf)

**Comment by ishakumar** [comment]
![Software Architecture Diagram](https://user-images.githubusercontent.com/55969546/76287400-a05caf80-6261-11ea-8ebd-b73d14aef441.png)
