### ISSUE TITLE
Producer Input

### ISSUE THREAD

**Issue by emccoy5** [cs210/ABC-Virtual-Anchor#6]
![image](https://user-images.githubusercontent.com/33084460/76036219-50e05180-5ef8-11ea-8ff0-6c8514ba2050.png)
React Web app.

**Comment by SajanaW** [comment]
The back end will have a text to speech REST end point:

> '/tts/'

It expects a POST call with the body formatted to be:

> multipart/form-data with one key/value pair being 'tts': 'text-you-want-the-api-to-speak'

Using the [Request Web APIs](https://developer.mozilla.org/en-US/docs/Web/API/Request), you can make a call like this:
 

`   function textToSpeech(){
        let formData = new FormData();
        formData.append("tts",document.getElementById("textArea").value )
        const request = new Request(
            'http://16b61b5c.ngrok.io/tts/', 
            { 
                method: 'POST',
                body: formData
            }
        );

        fetch(request)
            .then(response => {
                if (response.status === 200) {
                    return response.json()
                } else {
                    throw new Error('Could not get to Response Server');
                }
            })
            .then((data) => {
                audioURL = 'http://16b61b5c.ngrok.io/' + data
                const audio = new Audio(audioURL);
                audio.play();
            });
    }`
